services:
  - type: web
    name: uploadit-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"

  - type: web
    name: uploadit-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: serve -s frontend/build -l 3000
    envVars:
      - key: REACT_APP_API_URL
        value: https://uploadit-backend.onrender.com
      - key: DANGEROUSLY_DISABLE_HOST_CHECK
        value: "true"
